Repository cohenm0/hw-stats, pull requests merged in 2023-04, with the labels that each got.

#26 Create Acceptance.yml
  .github/workflows/PR-Acceptance.yml
  .pre-commit-config.yaml
  Makefile
  Pipfile
  Pipfile.lock
  hwstats/__init__.py
  hwstats/backend.py
  pyproject.toml
  tests/conftest.py
  tests/test_backend.py
  tests/test_frontend.py
Labels: Prototype, feature

#37 Adding changes for the layout of the processes
  hwstats/templates/index.html
Labels: enhancement

#40 UI table enhancements
  hwstats/frontend.py
  hwstats/models.py
  hwstats/monitor.py
  hwstats/templates/index.html
Labels: enhancement

#44 Prototype CPU plots
  .pre-commit-config.yaml
  Pipfile
  Pipfile.lock
  hwstats/backend.py
  hwstats/cli.py
  hwstats/frontend.py
  hwstats/models.py
  hwstats/templates/index.html
  hwstats/templates/plot.html
  pyproject.toml
  tests/test_cpu_load.py
  tests/test_models.py
Labels: enhancement

#53 Implemented Memory Plot
  hwstats/backend.py
  hwstats/frontend.py
  hwstats/models.py
  hwstats/templates/plot.html
Labels: enhancement, feature
